import 'dotenv/config';

export const env = {
  ZOHO_ANALYTICS_CLIENT_ID: process.env.ZOHO_ANALYTICS_CLIENT_ID || '',
  ZOHO_ANALYTICS_CLIENT_SECRET: process.env.ZOHO_ANALYTICS_CLIENT_SECRET || '',
  ZOHO_ANALYTICS_REFRESH_TOKEN: process.env.ZOHO_ANALYTICS_REFRESH_TOKEN || '',
  ZOHO_ACCOUNT_BASE_URL: process.env.ZOHO_ACCOUNT_BASE_URL || '',
  ZOHO_AUTH_ANALYTICS_URL: process.env.ZOHO_AUTH_ANALYTICS_URL || '',
  ZOHO_ANALYTICS_ORG_ID: process.env.ZOHO_ANALYTICS_ORG_ID || '',
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
};
