export const createReportSchema = {
  baseTableName: {type: 'String', required: true, description: 'Name of the base table used to create report'},
  title: {type: 'String', required: true, description: 'Name of the report'},
  description: {type: 'String', required: false, description: 'Description of the report'},
  reportType: {type: 'String', required: true, allowedValues: ['chart', 'pivot', 'summary']},
  chartType: {
    type: 'String',
    requiredIf: "reportType == 'chart'",
    allowedValues: {
      areaCharts: [
        'area',
        'area with points',
        'area without points',
        'smooth area',
        'smooth area with points',
        'smooth area without points',
        'stacked area',
        'stacked area with points',
        'stacked smooth area',
        'stacked smooth area with points',
        'stacked smooth area without points',
      ],
      barCharts: ['bar', 'horizontal bar', 'stacked bar', 'horizontal stacked bar'],
      bubbleCharts: ['bubble', 'packed bubble'],
      comboCharts: ['combo', 'combo bar with smooth line'],
      funnelPyramidCharts: ['funnel', 'pyramid'],
      lineCharts: ['line', 'line with points', 'line without points', 'smooth line', 'smooth line with points', 'smooth line without points', 'step'],
      mapCharts: ['map area', 'map bubble', 'map filled', 'map pie', 'map pie bubble', 'map bubble pie', 'map scatter', 'geo heat map'],
      pieRingCharts: ['pie', 'ring', 'semi pie', 'semi ring'],
      scatterCharts: ['scatter'],
      webCharts: ['web', 'web with fill', 'web without fill'],
      heatMaps: ['heat map'],
      otherCharts: ['butterfly', 'table chart'],
    },
  },
  axisColumns: {
    type: 'JSONArray',
    required: true,
    structure: {
      type: {
        type: 'String',
        required: true,
        allowedValuesByReportType: {chart: ['xAxis', 'yAxis', 'textAxis', 'colorAxis', 'toolTip'], pivot: ['row', 'column', 'data'], summary: ['groupBy', 'summarize']},
      },
      columnName: {type: 'String', required: true},
      operation: {
        type: 'String',
        required: true,
        allowedValuesByDataType: {
          Date: ['year', 'quarterYear', 'monthYear', 'weekYear', 'fullDate', 'dateTime', 'range', 'quarter', 'month', 'week', 'weekDay', 'day', 'hour', 'count', 'distinctCount'],
          Numeric: ['measure', 'dimension', 'range', 'sum', 'min', 'max', 'average', 'stdDev', 'median', 'mode', 'count', 'variance', 'distinctCount'],
          String: ['actual', 'count', 'distinctCount'],
        },
      },
    },
  },
  filters: {
    type: 'JSONArray',
    required: false,
    structure: {
      tableName: {type: 'String', required: true},
      columnName: {type: 'String', required: true},
      operation: {
        type: 'String',
        required: true,
        allowedValuesByDataType: {
          Date: ['actual', 'seasonal', 'relative'],
          Numeric: ['measure', 'dimension', 'range', 'actual', 'sum', 'min', 'max', 'average', 'stdDev', 'median', 'mode', 'count', 'variance', 'distinctCount'],
          String: ['actual', 'count', 'distinctCount'],
        },
      },
      filterType: {
        type: 'String',
        required: true,
        allowedValues: [
          'individualValues',
          'range',
          'ranking',
          'rankingPct',
          'dateRange',
          'year',
          'quarterYear',
          'monthYear',
          'weekYear',
          'quarter',
          'month',
          'week',
          'weekDay',
          'day',
          'hour',
          'dateTime',
        ],
      },
      values: {
        type: 'JSONArray',
        required: true,
        valueExamples: {
          ranking: ['Top 5'],
          range: ['1000 to 2000'],
          individualValues: ['20.97'],
          year: ['2012'],
          monthYear: ['Aug 2012'],
          weekYear: ['W03 2012'],
          quarterYear: ['Q1 2012'],
          actualDate: ['10 Mar 2012'],
          dateTime: ['10 Mar 2012 10:00:00'],
          dateRange: ['from 10 Dec 2013 00:00:00'],
          seasonalMonth: ['Jan'],
          relativeYear: ['Last Year'],
        },
      },
      exclude: {type: 'String', required: true, allowedValues: ['true', 'false']},
    },
  },
  userFilters: {
    type: 'JSONArray',
    required: false,
    structure: {
      tableName: {type: 'String', required: true},
      columnName: {type: 'String', required: true},
      operation: {
        type: 'String',
        required: true,
        allowedValuesByDataType: {
          Date: ['actual', 'seasonal', 'relative'],
          Numeric: ['measure', 'dimension', 'range', 'actual', 'sum', 'min', 'max', 'average', 'stdDev', 'median', 'mode', 'count', 'variance', 'distinctCount'],
          String: ['actual', 'count', 'distinctCount'],
        },
      },
    },
  },
  isAxisMerge: {type: 'String', required: false, allowedValues: ['true', 'false']},
  mergeAxisInfo: {type: 'String', requiredIf: 'isAxisMerge == true', formatExample: {axisIndex: [2, 3], labelName: 'Merge_axis'}},
};

export const mockConfigs = (tableName) => {
  return [
    {
      baseTableName: tableName,
      title: 'Monthly Sales and Profit Trend',
      description: 'Visualizes the revenue and profit growth over time to identify seasonal patterns and business performance.',
      reportType: 'chart',
      chartType: 'line',
      axisColumns: [
        {type: 'xAxis', columnName: 'Order Date', operation: 'monthYear'},
        {type: 'yAxis', columnName: 'Sales', operation: 'sum'},
        {type: 'yAxis', columnName: 'Profit', operation: 'sum'},
      ],
      userFilters: [
        {tableName: tableName, columnName: 'Region', operation: 'actual'},
        {tableName: tableName, columnName: 'Segment', operation: 'actual'},
      ],
      isAxisMerge: 'false',
    },
    {
      baseTableName: tableName,
      title: 'Geographic Profit Distribution',
      description: 'A map-based view showing profitability across different states to identify high and low performing regions.',
      reportType: 'chart',
      chartType: 'map filled',
      axisColumns: [
        {type: 'xAxis', columnName: 'State', operation: 'actual'},
        {type: 'yAxis', columnName: 'Profit', operation: 'sum'},
      ],
      userFilters: [
        {tableName: tableName, columnName: 'Category', operation: 'actual'},
        {tableName: tableName, columnName: 'Order Date', operation: 'actual'},
      ],
      isAxisMerge: 'false',
    },
    {
      baseTableName: tableName,
      title: 'Sales Contribution by Segment',
      description: 'Breakdown of total sales by customer segment to understand market share.',
      reportType: 'chart',
      chartType: 'ring',
      axisColumns: [
        {type: 'xAxis', columnName: 'Segment', operation: 'actual'},
        {type: 'yAxis', columnName: 'Sales', operation: 'sum'},
      ],
      userFilters: [{tableName: tableName, columnName: 'Region', operation: 'actual'}],
      isAxisMerge: 'false',
    },
    {
      baseTableName: tableName,
      title: 'Category and Sub-Category Sales Performance',
      description: 'Hierarchical view of sales across product categories and their specific sub-categories.',
      reportType: 'chart',
      chartType: 'stacked bar',
      axisColumns: [
        {type: 'xAxis', columnName: 'Category', operation: 'actual'},
        {type: 'yAxis', columnName: 'Sales', operation: 'sum'},
        {type: 'colorAxis', columnName: 'Sub-Category', operation: 'actual'},
      ],
      userFilters: [{tableName: tableName, columnName: 'Order Date', operation: 'actual'}],
      isAxisMerge: 'false',
    },
    {
      baseTableName: tableName,
      title: 'Discount vs Profitability Analysis',
      description: 'Analyzes the correlation between discount rates and resulting profit to evaluate pricing strategies.',
      reportType: 'chart',
      chartType: 'scatter',
      axisColumns: [
        {type: 'xAxis', columnName: 'Discount', operation: 'measure'},
        {type: 'yAxis', columnName: 'Profit', operation: 'sum'},
        {type: 'colorAxis', columnName: 'Category', operation: 'actual'},
      ],
      userFilters: [{tableName: tableName, columnName: 'Region', operation: 'actual'}],
      isAxisMerge: 'false',
    },
    {
      baseTableName: tableName,
      title: 'Top 10 Most Profitable Products',
      description: 'Identifies the leading products contributing to the bottom line.',
      reportType: 'chart',
      chartType: 'horizontal bar',
      axisColumns: [
        {type: 'xAxis', columnName: 'Product Name', operation: 'actual'},
        {type: 'yAxis', columnName: 'Profit', operation: 'sum'},
      ],
      filters: [{tableName: tableName, columnName: 'Profit', operation: 'sum', filterType: 'ranking', values: ['Top 10'], exclude: 'false'}],
      isAxisMerge: 'false',
    },
    {
      baseTableName: tableName,
      title: 'Shipping Mode and Region Efficiency',
      description: 'Pivot table analyzing order volume across different shipping modes and regions.',
      reportType: 'pivot',
      axisColumns: [
        {type: 'row', columnName: 'Region', operation: 'actual'},
        {type: 'column', columnName: 'Ship Mode', operation: 'actual'},
        {type: 'data', columnName: 'Order ID', operation: 'distinctCount'},
      ],
      userFilters: [{tableName: tableName, columnName: 'Category', operation: 'actual'}],
      isAxisMerge: 'false',
    },
    {
      baseTableName: tableName,
      title: 'Annual Sales Growth by Sub-Category',
      description: 'Compares yearly sales performance across different product sub-groups.',
      reportType: 'pivot',
      axisColumns: [
        {type: 'row', columnName: 'Sub-Category', operation: 'actual'},
        {type: 'column', columnName: 'Order Date', operation: 'year'},
        {type: 'data', columnName: 'Sales', operation: 'sum'},
      ],
      isAxisMerge: 'false',
    },
    {
      baseTableName: tableName,
      title: 'Product Category Performance Summary',
      description: 'Summary report of key metrics including total sales, profit, and average discount per category.',
      reportType: 'summary',
      axisColumns: [
        {type: 'groupBy', columnName: 'Category', operation: 'actual'},
        {type: 'summarize', columnName: 'Sales', operation: 'sum'},
        {type: 'summarize', columnName: 'Profit', operation: 'sum'},
        {type: 'summarize', columnName: 'Discount', operation: 'average'},
      ],
      isAxisMerge: 'false',
    },
    {
      baseTableName: tableName,
      title: 'Customer Loyalty and Order Frequency',
      description: 'Identifies top customers based on total sales and volume of orders.',
      reportType: 'chart',
      chartType: 'bubble',
      axisColumns: [
        {type: 'xAxis', columnName: 'Customer Name', operation: 'actual'},
        {type: 'yAxis', columnName: 'Sales', operation: 'sum'},
        {type: 'colorAxis', columnName: 'Quantity', operation: 'sum'},
      ],
      filters: [{tableName: tableName, columnName: 'Sales', operation: 'sum', filterType: 'ranking', values: ['Top 20'], exclude: 'false'}],
      isAxisMerge: 'false',
    },
  ];
};

export const uploadedDataSchema = {
  'Row ID': 'Positive Number',
  'Order ID': 'Plain Text',
  'Order Date': 'Date',
  'Ship Date': 'Date',
  'Ship Mode': 'Plain Text',
  'Customer ID': 'Plain Text',
  'Customer Name': 'Plain Text',
  Segment: 'Plain Text',
  Country: 'Geo column',
  City: 'Plain Text',
  State: 'Geo column',
  'Postal Code': 'Positive Number',
  Region: 'Plain Text',
  'Product ID': 'Plain Text',
  Category: 'Plain Text',
  'Sub-Category': 'Plain Text',
  'Product Name': 'Plain Text',
  Sales: 'Decimal Number',
  Quantity: 'Positive Number',
  Discount: 'Decimal Number',
  Profit: 'Decimal Number',
};
